on: [ pull_request ]
name: Style Checker

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: php-cs-fixer:3.15, cs2pr

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
